package com.example.myfirstnavalbattle.model;

/**
 * Thread for background AI ship placement.
 * While the player manually places their ships, this thread
 * generates the AI board concurrently.
 * 
 * Demonstrates: Concurrency, volatile synchronization, and Thread usage.
 * 
 * @author David - Brandon
 */
public class AIShipPlacementThread extends Thread {

    private Board aiBoard;
    private volatile boolean isComplete = false;
    private volatile boolean shouldStart = false;
    private final Object lock = new Object();

    /**
     * AI Ship Placement Thread Constructor
     */
    public AIShipPlacementThread() {
        super("AI-Ship-Placement-Thread");
        System.out.println("[AI THREAD] Thread created and ready to start");
    }

    @Override
    public void run() {
        System.out.println("[AI THREAD] Thread running, waiting for signal to start...");

        // Wait for start signal
        synchronized (lock) {
            while (!shouldStart) {
                try {
                    lock.wait();
                } catch (InterruptedException e) {
                    System.err.println("[AI THREAD] Interrupted while waiting");
                    Thread.currentThread().interrupt();
                    return;
                }
            }
        }

        System.out.println("[AI THREAD] Signal received! Starting ship placement...");

        try {
            // Simulate small delay to make concurrency visible
            Thread.sleep(500);

            // Create and generate AI board
            aiBoard = new Board();

            System.out.println("[AI THREAD] ✓ AI Board generated successfully");

            // Mark as complete
            synchronized (lock) {
                isComplete = true;
                lock.notifyAll();
            }

            System.out.println("[AI THREAD] Placement complete!");

        } catch (InterruptedException e) {
            System.err.println("[AI THREAD] Interrupted during placement");
            Thread.currentThread().interrupt();
        } catch (Exception e) {
            System.err.println("[AI THREAD] Error during placement: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Signals the thread to start placement
     */
    public void signalStart() {
        synchronized (lock) {
            shouldStart = true;
            lock.notifyAll();
        }
        System.out.println("[MAIN THREAD] Signal sent to AI thread to start");
    }

    /**
     * Waits for the thread to complete placement
     * 
     * @throws InterruptedException if thread is interrupted while waiting
     */
    public void waitForCompletion() throws InterruptedException {
        synchronized (lock) {
            while (!isComplete) {
                System.out.println("[MAIN THREAD] Waiting for AI to complete placement...");
                lock.wait();
            }
        }
        System.out.println("[MAIN THREAD] AI has completed placement");
    }

    /**
     * Gets the board generated by AI
     * 
     * @return Generated Board, or null if not yet complete
     */
    public Board getAIBoard() {
        return aiBoard;
    }

    /**
     * Checks if placement is complete
     * 
     * @return true if complete, false otherwise
     */
    public boolean isComplete() {
        return isComplete;
    }
}
